name: pycodestyle

on:
  push:
    branches: [python3]
  pull_request:
    branches: [python3]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-1

      - name: pycodestyle
        run: |
          pip install pycodestyle
          pycodestyle --select E20,E211,E22,E224,E241,E242,E27,E225,E226,E227,E228,E231,E301,E302,E303,E304,E305,E306,W291,W292,W293,W391 .
